-- Idempotent PostgreSQL script for DMBPortfolio
-- Safe to run multiple times.
-- NOTE: CREATE DATABASE cannot run inside a transaction/DO block.
-- Run this first (once) while connected to postgres/default db:
--   CREATE DATABASE "DMBPortfolio";
-- Then connect to DMBPortfolio and run the rest.

-- In psql:
-- \c "DMBPortfolio"

-- 0) Drop & recreate (clean reset)
DROP TABLE IF EXISTS "AccountActivationToken";
DROP TABLE IF EXISTS "PasswordResetToken";
DROP TABLE IF EXISTS "RevokedToken";
DROP TABLE IF EXISTS "Project";
DROP TABLE IF EXISTS "ProjectType";
DROP TABLE IF EXISTS "UserDetails";
DROP TABLE IF EXISTS "User";

-- 1) Create tables

CREATE TABLE "User"
(
    "UserId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"    VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "PasswordSalt" VARCHAR(255) NOT NULL,
    "FirstName"   VARCHAR(100) NOT NULL,
    "LastName"    VARCHAR(100) NOT NULL,
    "Email"       VARCHAR(255) NOT NULL UNIQUE,
    "ContactNo"   VARCHAR(30),
    "Activated"   BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "PasswordResetToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_PasswordResetToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

CREATE TABLE "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");



-- 8) Incremental: add AccountActivationToken on an existing database (skip if table already exists)
CREATE TABLE IF NOT EXISTS "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");

-- 9) Incremental migration: normalize Project.Type into ProjectType table
CREATE TABLE IF NOT EXISTS "ProjectType"
(
    "ProjectTypeId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TypeName"      VARCHAR(100) NOT NULL UNIQUE,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'Project'
          AND column_name = 'Type'
    ) THEN
        INSERT INTO "ProjectType" ("TypeName")
        SELECT DISTINCT "Type"
        FROM "Project"
        WHERE "Type" IS NOT NULL
        ON CONFLICT ("TypeName") DO NOTHING;

        ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ProjectTypeId" INTEGER;

        UPDATE "Project" p
        SET "ProjectTypeId" = pt."ProjectTypeId"
        FROM "ProjectType" pt
        WHERE pt."TypeName" = p."Type"
          AND p."ProjectTypeId" IS NULL;

        ALTER TABLE "Project" ALTER COLUMN "ProjectTypeId" SET NOT NULL;
        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "FK_Project_ProjectType";
        ALTER TABLE "Project"
            ADD CONSTRAINT "FK_Project_ProjectType"
                FOREIGN KEY ("ProjectTypeId") REFERENCES "ProjectType" ("ProjectTypeId")
                ON DELETE CASCADE;

        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "UQ_Project_User_Name_Type";
        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "UQ_Project_User_Name_ProjectType";
        ALTER TABLE "Project"
            ADD CONSTRAINT "UQ_Project_User_Name_ProjectType" UNIQUE ("UserId", "Name", "ProjectTypeId");

        ALTER TABLE "Project" DROP COLUMN IF EXISTS "Type";
    END IF;
END $$;



CREATE TABLE "UserDetails"
(
    "UserDetailsId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Description"   TEXT,
    "Skills"        TEXT, -- comma separated values
    "Video"         TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_UserDetails_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_UserDetails_UserId" ON "UserDetails" ("UserId");

CREATE TABLE IF NOT EXISTS "ProjectType"
(
    "ProjectTypeId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TypeName"      VARCHAR(100) NOT NULL UNIQUE,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Project"
(
    "ProjectId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          INTEGER NOT NULL,
    "Name"            VARCHAR(200) NOT NULL,
    "ProjectTypeId"   INTEGER NOT NULL,
    "ProjectDetails"  TEXT, -- comma separated values
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Project_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE,
    CONSTRAINT "FK_Project_ProjectType"
        FOREIGN KEY ("ProjectTypeId") REFERENCES "ProjectType" ("ProjectTypeId")
        ON DELETE CASCADE
);

CREATE TABLE "RevokedToken"
(
    "RevokedTokenId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Jti"           TEXT NOT NULL UNIQUE,
    "ExpiresAt"     TIMESTAMPTZ NOT NULL,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "Project"
    ADD CONSTRAINT "UQ_Project_User_Name_ProjectType" UNIQUE ("UserId", "Name", "ProjectTypeId");

-- 3) Seed Users (based on ProfileController response)
-- Actual password for the seeded user: Password@123
INSERT INTO "User" ("Username", "PasswordHash", "PasswordSalt", "FirstName", "LastName", "Email", "ContactNo", "Activated", "CreatedAt")
VALUES
('deobernal@gmail.com', 'vHgVB+7WP1+kaDN0PgGjr0p+sqtr1avXf+WGkpRlYb6eI6PdvsU/BuNMyus+sJX2PN3XWOAq67s4HaCs9N1f4w==', 'nL3mQ8vX1pR7kD5sT2wB9A==', 'Deo', 'Bernal', 'deobernal@gmail.com', '+63 925 455 6063', TRUE, NOW())
ON CONFLICT ("Username") DO UPDATE
SET
    "PasswordHash" = EXCLUDED."PasswordHash",
    "PasswordSalt" = EXCLUDED."PasswordSalt",
    "FirstName" = EXCLUDED."FirstName",
    "LastName"  = EXCLUDED."LastName",
    "Email"     = EXCLUDED."Email",
    "ContactNo" = EXCLUDED."ContactNo",
    "Activated" = EXCLUDED."Activated",
    "CreatedAt" = EXCLUDED."CreatedAt";

-- 4) Seed UserDetails (portfolio summary + skills + video)
INSERT INTO "UserDetails" ("UserId", "Description", "Skills", "Video")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Senior Full-Stack .NET Developer with 19+ years of experience building scalable web applications using .NET, React, Angular, and SQL. Experienced in ERP, banking, and enterprise systems with strong focus on performance and maintainability',
    'C#,.NET Core,AngularJS,Angular,React,.NET Core C#,SQL,cloud-native technologies,AI-assisted development,Cursor,GitHub Copilot,React Native,ASP.NET C#,MVC,MS SQL,MongoDB,Docker,RabbitMQ,Google Cloud Platform,HubSpot,PingIdentity,REST APIs,Azure,Cloud Functions,Datastore,Pub/Sub,ARM/Bicep-style deployments,WCF,EF6,IoC/DI,Bootstrap,Umbraco,ASP Classic,JavaScript,Flash,Telerik controls,ORM,XML,SQL Server,AJAX,VB6,Crystal Reports,VB.NET',
    'https://go.screenpal.com/watch/cOflXKnOnrx'
)
ON CONFLICT ("UserId") DO UPDATE
SET
    "Description" = EXCLUDED."Description",
    "Skills"      = EXCLUDED."Skills",
    "Video"       = EXCLUDED."Video";

-- 5) Seed ProjectType values
INSERT INTO "ProjectType" ("TypeName")
VALUES
('🧳 Travel Industry Systems'),
('💰 Finance & Banking Systems'),
('🌐 Web & CMS Platforms'),
('🏢 Enterprise & Business Systems'),
('🛒 E-Commerce & Customer-Facing Apps')
ON CONFLICT ("TypeName") DO NOTHING;

-- 6) Seed Projects (matches ProfileController project categories)
INSERT INTO "Project" ("UserId", "ProjectTypeId", "Name", "ProjectDetails")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🧳 Travel Industry Systems'),
    'Enterprise Management System',
    'Travel agent management platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🧳 Travel Industry Systems'),
    'Content Management System (Travel)',
    'CMS for travel operations'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'MortgageChoice',
    'Brokerage management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'CustomerData.Contact',
    'Cloud-based customer data microservices (CRM sync)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Tardis Omniverse',
    'Lead generation platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Rubik',
    'Banking and credit card management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Internet Banking System',
    'Online banking platform (web & mobile)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🌐 Web & CMS Platforms'),
    'Content Management System (Umbraco)',
    'CMS for websites'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🌐 Web & CMS Platforms'),
    'Project Management System (AngularJS)',
    'Internal team management tool'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Enterprise Accounting & HR System',
    'ERP for accounting, HR, purchasing'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Training Management System',
    'Employee training platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Document Management System',
    'File storage, search, and PDF export system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Client/Project/Task Management System',
    'Business workflow system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🛒 E-Commerce & Customer-Facing Apps'),
    'eCommerce Platform (AspDotNetStorefront)',
    'Online shopping system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🛒 E-Commerce & Customer-Facing Apps'),
    'Payment Gateway Integration Enhancements',
    'Fixes and improvements'
)
ON CONFLICT ("UserId", "Name", "ProjectTypeId") DO UPDATE
SET
    "ProjectDetails" = EXCLUDED."ProjectDetails";

-- 6) Verification queries
SELECT * FROM "User" ORDER BY "UserId";
SELECT * FROM "UserDetails" ORDER BY "UserDetailsId";
SELECT * FROM "ProjectType" ORDER BY "ProjectTypeId";
SELECT * FROM "Project" ORDER BY "ProjectId";
SELECT * FROM "PasswordResetToken" ORDER BY "TokenId";

-- 7) Incremental: add PasswordResetToken on an existing database (skip if table already exists)
-- CREATE TABLE IF NOT EXISTS "PasswordResetToken"
-- (
--     "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "UserId"      INTEGER NOT NULL,
--     "Token"       VARCHAR(256) NOT NULL,
--     "ExpiresAt"   TIMESTAMPTZ NOT NULL,
--     "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
--     "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT "FK_PasswordResetToken_User"
--         FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
--         ON DELETE CASCADE
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

