-- Idempotent PostgreSQL script for DMBPortfolio
-- Safe to run multiple times.
-- NOTE: CREATE DATABASE cannot run inside a transaction/DO block.
-- Run this first (once) while connected to postgres/default db:
--   CREATE DATABASE "DMBPortfolio";
-- Then connect to DMBPortfolio and run the rest.

-- In psql:
-- \c "DMBPortfolio"

-- 0) Drop & recreate (clean reset)
DROP TABLE IF EXISTS "AccountActivationToken";
DROP TABLE IF EXISTS "PasswordResetToken";
DROP TABLE IF EXISTS "RevokedToken";
DROP TABLE IF EXISTS "Education";
DROP TABLE IF EXISTS "WorkHistory";
DROP TABLE IF EXISTS "Affiliation";
DROP TABLE IF EXISTS "Project";
DROP TABLE IF EXISTS "ProjectType";
DROP TABLE IF EXISTS "UserDetails";
DROP TABLE IF EXISTS "User";

-- 1) Create tables

CREATE TABLE "User"
(
    "UserId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"    VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "PasswordSalt" VARCHAR(255) NOT NULL,
    "FirstName"   VARCHAR(100) NOT NULL,
    "LastName"    VARCHAR(100) NOT NULL,
    "Email"       VARCHAR(255) NOT NULL UNIQUE,
    "Address"     VARCHAR(255),
    "ContactNo"   VARCHAR(30),
    "Activated"   BOOLEAN NOT NULL DEFAULT TRUE,
    "IsViewable"  BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX "UX_User_Username_FirstName_LastName" ON "User" ("Username", "FirstName", "LastName");

CREATE TABLE "PasswordResetToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_PasswordResetToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

CREATE TABLE "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");



-- 8) Incremental: add AccountActivationToken on an existing database (skip if table already exists)
CREATE TABLE IF NOT EXISTS "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");

-- 8.1) Incremental: add visibility + uniqueness constraints on existing User table
ALTER TABLE "User"
    ADD COLUMN IF NOT EXISTS "IsViewable" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "User"
    ADD COLUMN IF NOT EXISTS "Address" VARCHAR(255);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_User_Username_FirstName_LastName" ON "User" ("Username", "FirstName", "LastName");

-- 9) Incremental migration: normalize Project.Type into ProjectType table
CREATE TABLE IF NOT EXISTS "ProjectType"
(
    "ProjectTypeId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TypeName"      VARCHAR(100) NOT NULL UNIQUE,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'Project'
          AND column_name = 'Type'
    ) THEN
        INSERT INTO "ProjectType" ("TypeName")
        SELECT DISTINCT "Type"
        FROM "Project"
        WHERE "Type" IS NOT NULL
        ON CONFLICT ("TypeName") DO NOTHING;

        ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ProjectTypeId" INTEGER;

        UPDATE "Project" p
        SET "ProjectTypeId" = pt."ProjectTypeId"
        FROM "ProjectType" pt
        WHERE pt."TypeName" = p."Type"
          AND p."ProjectTypeId" IS NULL;

        ALTER TABLE "Project" ALTER COLUMN "ProjectTypeId" SET NOT NULL;
        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "FK_Project_ProjectType";
        ALTER TABLE "Project"
            ADD CONSTRAINT "FK_Project_ProjectType"
                FOREIGN KEY ("ProjectTypeId") REFERENCES "ProjectType" ("ProjectTypeId")
                ON DELETE CASCADE;

        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "UQ_Project_User_Name_Type";
        ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "UQ_Project_User_Name_ProjectType";
        ALTER TABLE "Project"
            ADD CONSTRAINT "UQ_Project_User_Name_ProjectType" UNIQUE ("UserId", "Name", "ProjectTypeId");

        ALTER TABLE "Project" DROP COLUMN IF EXISTS "Type";
    END IF;
END $$;



CREATE TABLE "UserDetails"
(
    "UserDetailsId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Description"   TEXT,
    "Skills"        TEXT, -- comma separated values
    "Video"         TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_UserDetails_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_UserDetails_UserId" ON "UserDetails" ("UserId");

CREATE TABLE IF NOT EXISTS "ProjectType"
(
    "ProjectTypeId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TypeName"      VARCHAR(100) NOT NULL UNIQUE,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Project"
(
    "ProjectId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          INTEGER NOT NULL,
    "Name"            VARCHAR(200) NOT NULL,
    "ProjectTypeId"   INTEGER NOT NULL,
    "ProjectDetails"  TEXT, -- comma separated values
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Project_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE,
    CONSTRAINT "FK_Project_ProjectType"
        FOREIGN KEY ("ProjectTypeId") REFERENCES "ProjectType" ("ProjectTypeId")
        ON DELETE CASCADE
);

CREATE TABLE "WorkHistory"
(
    "WorkHistoryId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Company"       VARCHAR(200) NOT NULL,
    "Position"      VARCHAR(200) NOT NULL,
    "FromDate"      DATE,
    "ToDate"        DATE,
    "JobDescription" TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_WorkHistory_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

-- Idempotency helpers (so seed can use ON CONFLICT safely)
CREATE UNIQUE INDEX IF NOT EXISTS "UX_WorkHistory_User_Company_Position_FromDate"
    ON "WorkHistory" ("UserId", "Company", "Position", "FromDate");

CREATE TABLE "Education"
(
    "EducationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "School"      VARCHAR(200) NOT NULL,
    "Address"     VARCHAR(255),
    "CourseTaken" VARCHAR(255),
    "StartDate"   DATE,
    "EndDate"     DATE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Education_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

-- Idempotency helpers (so seed can use ON CONFLICT safely)
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Education_User_School_Course_StartDate"
    ON "Education" ("UserId", "School", "CourseTaken", "StartDate");

CREATE TABLE "Affiliation"
(
    "AffiliationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Organization"  VARCHAR(200) NOT NULL,
    "Title"         VARCHAR(200) NOT NULL,
    "IssueDate"     DATE,
    "Details"       TEXT NOT NULL,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Affiliation_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Affiliation_User_Org_Title_IssueDate"
    ON "Affiliation" ("UserId", "Organization", "Title", "IssueDate");

CREATE TABLE IF NOT EXISTS "WorkHistory"
(
    "WorkHistoryId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Company"       VARCHAR(200) NOT NULL,
    "Position"      VARCHAR(200) NOT NULL,
    "FromDate"      DATE,
    "ToDate"        DATE,
    "JobDescription" TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_WorkHistory_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Education"
(
    "EducationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "School"      VARCHAR(200) NOT NULL,
    "Address"     VARCHAR(255),
    "CourseTaken" VARCHAR(255),
    "StartDate"   DATE,
    "EndDate"     DATE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Education_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Affiliation"
(
    "AffiliationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Organization"  VARCHAR(200) NOT NULL,
    "Title"         VARCHAR(200) NOT NULL,
    "IssueDate"     DATE,
    "Details"       TEXT NOT NULL,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Affiliation_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE TABLE "RevokedToken"
(
    "RevokedTokenId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER,
    "Jti"           TEXT NOT NULL UNIQUE,
    "ExpiresAt"     TIMESTAMPTZ NOT NULL,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_RevokedToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_RevokedToken_UserId" ON "RevokedToken" ("UserId");

-- Incremental patch for existing databases
ALTER TABLE "RevokedToken"
    ADD COLUMN IF NOT EXISTS "UserId" INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_RevokedToken_User'
    ) THEN
        ALTER TABLE "RevokedToken"
            ADD CONSTRAINT "FK_RevokedToken_User"
                FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
                ON DELETE CASCADE;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS "IX_RevokedToken_UserId" ON "RevokedToken" ("UserId");

ALTER TABLE "Project"
    ADD CONSTRAINT "UQ_Project_User_Name_ProjectType" UNIQUE ("UserId", "Name", "ProjectTypeId");

-- 3) Seed Users (based on ProfileController response)
-- Actual password for the seeded user: Password@123
INSERT INTO "User" ("Username", "PasswordHash", "PasswordSalt", "FirstName", "LastName", "Email", "Address", "ContactNo", "Activated", "IsViewable", "CreatedAt")
VALUES
('deobernal@gmail.com', 'vHgVB+7WP1+kaDN0PgGjr0p+sqtr1avXf+WGkpRlYb6eI6PdvsU/BuNMyus+sJX2PN3XWOAq67s4HaCs9N1f4w==', 'nL3mQ8vX1pR7kD5sT2wB9A==', 'Deo', 'Bernal', 'deobernal@gmail.com', NULL, '+63 925 455 6063', TRUE, TRUE, NOW())
ON CONFLICT ("Username") DO UPDATE
SET
    "PasswordHash" = EXCLUDED."PasswordHash",
    "PasswordSalt" = EXCLUDED."PasswordSalt",
    "FirstName" = EXCLUDED."FirstName",
    "LastName"  = EXCLUDED."LastName",
    "Email"     = EXCLUDED."Email",
    "Address"   = EXCLUDED."Address",
    "ContactNo" = EXCLUDED."ContactNo",
    "Activated" = EXCLUDED."Activated",
    "IsViewable" = EXCLUDED."IsViewable",
    "CreatedAt" = EXCLUDED."CreatedAt";

-- 4) Seed UserDetails (portfolio summary + skills + video)
INSERT INTO "UserDetails" ("UserId", "Description", "Skills", "Video")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Senior Full-Stack .NET Developer with 19+ years of experience building scalable web applications using .NET, React, Angular, and SQL. Experienced in ERP, banking, and enterprise systems with strong focus on performance and maintainability',
    'C#,.NET Core,AngularJS,Angular,React,.NET Core C#,SQL,cloud-native technologies,AI-assisted development,Cursor,GitHub Copilot,React Native,ASP.NET C#,MVC,MS SQL,MongoDB,Docker,RabbitMQ,Google Cloud Platform,HubSpot,PingIdentity,REST APIs,Azure,Cloud Functions,Datastore,Pub/Sub,ARM/Bicep-style deployments,WCF,EF6,IoC/DI,Bootstrap,Umbraco,ASP Classic,JavaScript,Flash,Telerik controls,ORM,XML,SQL Server,AJAX,VB6,Crystal Reports,VB.NET',
    'https://go.screenpal.com/watch/cOflXKnOnrx'
)
ON CONFLICT ("UserId") DO UPDATE
SET
    "Description" = EXCLUDED."Description",
    "Skills"      = EXCLUDED."Skills",
    "Video"       = EXCLUDED."Video";

-- 4.1) Seed WorkHistory (resume)
INSERT INTO "WorkHistory" ("UserId", "Company", "Position", "FromDate", "ToDate", "JobDescription")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Ezerec',
    'Senior Software Developer (Hybrid)',
    DATE '2023-04-01',
    DATE '2026-03-31',
    'Developed and maintained high-performance web applications using React 17.0.2, React Native, .NET Core (C#) MVC and MS SQL, leveraging AI-driven tools (Cursor, GitHub Copilot) to accelerate coding speed and efficiency. Project (Travel Industry): Enterprise Management System.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Cloudstaff',
    'Senior Software Engineer (WFH)',
    DATE '2020-11-02',
    DATE '2023-06-02',
    'Conducted technical analysis, implemented enhancements, and followed coding standards. Tech stack: Angular 4/9/12/13/14, .NET Core C#, MVC, MS SQL, MongoDB, Docker, RabbitMQ, GCP, HubSpot, PingIdentity. Projects: MortgageChoice, CustomerData.Contact, Tardis Omniverse.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Ezerec',
    'Senior Software Developer - TL (On-site)',
    DATE '2017-02-01',
    DATE '2020-10-30',
    'Led ERP web app team in development/testing/support, migrated legacy systems to Angular/React/.NET Core/MS SQL, organized agile delivery, enforced coding standards, and coached best practices. Projects: Content Management System, Enterprise Management System.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Cloudstaff',
    'Senior Software Engineer (On-site)',
    DATE '2015-11-01',
    DATE '2017-01-31',
    'Developed internet banking apps using ASP.NET C#, WCF, and MS SQL; contributed to credit card management system using REST APIs, WCF, EF6, and IoC/DI. Project: Rubik.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Indigo Web',
    'Back /Front-End Web Developer (WFH)',
    DATE '2009-06-22',
    DATE '2015-08-27',
    'Developed CMS, e-commerce, and web apps using ASP.NET C#/VB.NET, MVC, Umbraco, and MS SQL; built internal AngularJS project management app; planned systems and database designs; implemented basic SEO and responsive UI.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Team Power International',
    'Senior Web Developer (Dubai)',
    DATE '2007-08-31',
    DATE '2009-04-03',
    'Maintained/enhanced e-commerce website and payment gateway using ASP.NET C#, XML, and MS SQL; implemented DB logic; developed chat app (AJAX); designed and built a training management system.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'CompuEx',
    'Software Engineer (Bahrain)',
    DATE '2006-07-11',
    DATE '2007-06-21',
    'Developed and maintained ERP systems (accounting, HR, purchasing) using VB6, Crystal Reports, and MS SQL; built database migration tools; maintained/debugged POS systems.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Amertron Incorporated',
    'Software Programmer (On-site)',
    DATE '2006-02-27',
    DATE '2006-07-10',
    'Maintained and enhanced ERP systems (lot tracking, accounting, warehouse, HR, purchasing); customized lot tracking modules using ASP.NET C#.'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Enigma Technologies',
    'Software Programmer (On-site)',
    DATE '2005-01-03',
    DATE '2006-02-21',
    'Developed web-based applications including a weekly schedule “Locator” and “Express Medic” (patient records + appointment scheduling) using VB.NET/ASP.NET and SQL Server; enhanced POS software using VB6 and Crystal Reports.'
)
ON CONFLICT ("UserId", "Company", "Position", "FromDate") DO UPDATE
SET
    "ToDate" = EXCLUDED."ToDate",
    "JobDescription" = EXCLUDED."JobDescription";

-- 4.2) Seed Education (resume)
INSERT INTO "Education" ("UserId", "School", "Address", "CourseTaken", "StartDate", "EndDate")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Holy Angel University',
    'Angeles City, Philippines',
    'Bachelor of Science in Electronics and Communications Engineering',
    DATE '1993-01-01',
    DATE '1998-12-31'
)
ON CONFLICT ("UserId", "School", "CourseTaken", "StartDate") DO UPDATE
SET
    "Address" = EXCLUDED."Address",
    "EndDate" = EXCLUDED."EndDate";

-- 4.3) Seed Affiliations (resume)
INSERT INTO "Affiliation" ("UserId", "Organization", "Title", "IssueDate", "Details")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Professional Regulations Commission (PRC)',
    'Electronics and Communications Engineer',
    DATE '1998-11-05',
    'Electronics and Communications Engineer Licensure Examination (Nov 4–5, 1998), Manila, Philippines. License Number: 0017233.'
)
ON CONFLICT ("UserId", "Organization", "Title", "IssueDate") DO UPDATE
SET
    "Details" = EXCLUDED."Details";

-- 5) Seed ProjectType values
INSERT INTO "ProjectType" ("TypeName")
VALUES
('🧳 Travel Industry Systems'),
('💰 Finance & Banking Systems'),
('🌐 Web & CMS Platforms'),
('🏢 Enterprise & Business Systems'),
('🛒 E-Commerce & Customer-Facing Apps')
ON CONFLICT ("TypeName") DO NOTHING;

-- 6) Seed Projects (matches ProfileController project categories)
INSERT INTO "Project" ("UserId", "ProjectTypeId", "Name", "ProjectDetails")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🧳 Travel Industry Systems'),
    'Enterprise Management System',
    'Travel agent management platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🧳 Travel Industry Systems'),
    'Content Management System (Travel)',
    'CMS for travel operations'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'MortgageChoice',
    'Brokerage management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'CustomerData.Contact',
    'Cloud-based customer data microservices (CRM sync)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Tardis Omniverse',
    'Lead generation platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Rubik',
    'Banking and credit card management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '💰 Finance & Banking Systems'),
    'Internet Banking System',
    'Online banking platform (web & mobile)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🌐 Web & CMS Platforms'),
    'Content Management System (Umbraco)',
    'CMS for websites'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🌐 Web & CMS Platforms'),
    'Project Management System (AngularJS)',
    'Internal team management tool'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Enterprise Accounting & HR System',
    'ERP for accounting, HR, purchasing'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Training Management System',
    'Employee training platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Document Management System',
    'File storage, search, and PDF export system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🏢 Enterprise & Business Systems'),
    'Client/Project/Task Management System',
    'Business workflow system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🛒 E-Commerce & Customer-Facing Apps'),
    'eCommerce Platform (AspDotNetStorefront)',
    'Online shopping system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    (SELECT "ProjectTypeId" FROM "ProjectType" WHERE "TypeName" = '🛒 E-Commerce & Customer-Facing Apps'),
    'Payment Gateway Integration Enhancements',
    'Fixes and improvements'
)
ON CONFLICT ("UserId", "Name", "ProjectTypeId") DO UPDATE
SET
    "ProjectDetails" = EXCLUDED."ProjectDetails";

-- 6) Verification queries
SELECT * FROM "User" ORDER BY "UserId";
SELECT * FROM "UserDetails" ORDER BY "UserDetailsId";
SELECT * FROM "ProjectType" ORDER BY "ProjectTypeId";
SELECT * FROM "Project" ORDER BY "ProjectId";
SELECT * FROM "PasswordResetToken" ORDER BY "TokenId";

-- 7) Incremental: add PasswordResetToken on an existing database (skip if table already exists)
-- CREATE TABLE IF NOT EXISTS "PasswordResetToken"
-- (
--     "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "UserId"      INTEGER NOT NULL,
--     "Token"       VARCHAR(256) NOT NULL,
--     "ExpiresAt"   TIMESTAMPTZ NOT NULL,
--     "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
--     "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT "FK_PasswordResetToken_User"
--         FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
--         ON DELETE CASCADE
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

-- 10) Account deletion procedure (deletes user + all related records)
DROP PROCEDURE IF EXISTS "SP_DeleteAccount"(INTEGER);

CREATE OR REPLACE PROCEDURE "SP_DeleteAccount"(IN p_user_id INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    -- Explicit delete order across all user-related tables.
    DELETE FROM "RevokedToken" WHERE "UserId" = p_user_id;
    DELETE FROM "AccountActivationToken" WHERE "UserId" = p_user_id;
    DELETE FROM "PasswordResetToken" WHERE "UserId" = p_user_id;
    DELETE FROM "UserDetails" WHERE "UserId" = p_user_id;
    DELETE FROM "Project" WHERE "UserId" = p_user_id;
    DELETE FROM "WorkHistory" WHERE "UserId" = p_user_id;
    DELETE FROM "Education" WHERE "UserId" = p_user_id;
    DELETE FROM "Affiliation" WHERE "UserId" = p_user_id;
    DELETE FROM "User" WHERE "UserId" = p_user_id;

    -- Keep the lookup table clean by removing project types no longer referenced.
    DELETE FROM "ProjectType" pt
    WHERE NOT EXISTS (
        SELECT 1
        FROM "Project" p
        WHERE p."ProjectTypeId" = pt."ProjectTypeId"
    );
END;
$$;

