-- Idempotent PostgreSQL script for DMBPortfolio
-- Safe to run multiple times.
-- NOTE: CREATE DATABASE cannot run inside a transaction/DO block.
-- Run this first (once) while connected to postgres/default db:
--   CREATE DATABASE "DMBPortfolio";
-- Then connect to DMBPortfolio and run the rest.

-- In psql:
-- \c "DMBPortfolio"

-- 0) Drop & recreate (clean reset)
DROP TABLE IF EXISTS "AccountActivationToken";
DROP TABLE IF EXISTS "PasswordResetToken";
DROP TABLE IF EXISTS "RevokedToken";
DROP TABLE IF EXISTS "Project";
DROP TABLE IF EXISTS "UserDetails";
DROP TABLE IF EXISTS "User";

-- 1) Create tables

CREATE TABLE "User"
(
    "UserId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"    VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "PasswordSalt" VARCHAR(255) NOT NULL,
    "FirstName"   VARCHAR(100) NOT NULL,
    "LastName"    VARCHAR(100) NOT NULL,
    "Email"       VARCHAR(255) NOT NULL UNIQUE,
    "ContactNo"   VARCHAR(30),
    "Activated"   BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "PasswordResetToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_PasswordResetToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

CREATE TABLE "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");



-- 8) Incremental: add AccountActivationToken on an existing database (skip if table already exists)
-- CREATE TABLE IF NOT EXISTS "AccountActivationToken"
-- (
--     "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "UserId"      INTEGER NOT NULL,
--     "Token"       VARCHAR(256) NOT NULL,
--     "ExpiresAt"   TIMESTAMPTZ NOT NULL,
--     "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
--     "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT "FK_AccountActivationToken_User"
--         FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
--         ON DELETE CASCADE
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS "UX_AccountActivationToken_Token" ON "AccountActivationToken" ("Token");



CREATE TABLE "UserDetails"
(
    "UserDetailsId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER NOT NULL,
    "Description"   TEXT,
    "Skills"        TEXT, -- comma separated values
    "Video"         TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_UserDetails_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UX_UserDetails_UserId" ON "UserDetails" ("UserId");

CREATE TABLE "Project"
(
    "ProjectId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"          INTEGER NOT NULL,
    "Name"            VARCHAR(200) NOT NULL,
    "Type"            VARCHAR(100) NOT NULL,
    "ProjectDetails"  TEXT, -- comma separated values
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Project_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE TABLE "RevokedToken"
(
    "RevokedTokenId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Jti"           TEXT NOT NULL UNIQUE,
    "ExpiresAt"     TIMESTAMPTZ NOT NULL,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "Project"
    ADD CONSTRAINT "UQ_Project_User_Name_Type" UNIQUE ("UserId", "Name", "Type");

-- 3) Seed Users (based on ProfileController response)
-- Actual password for the seeded user: Password@123
INSERT INTO "User" ("Username", "PasswordHash", "PasswordSalt", "FirstName", "LastName", "Email", "ContactNo", "Activated", "CreatedAt")
VALUES
('deobernal@gmail.com', 'vHgVB+7WP1+kaDN0PgGjr0p+sqtr1avXf+WGkpRlYb6eI6PdvsU/BuNMyus+sJX2PN3XWOAq67s4HaCs9N1f4w==', 'nL3mQ8vX1pR7kD5sT2wB9A==', 'Deo', 'Bernal', 'deobernal@gmail.com', '+63 925 455 6063', TRUE, NOW())
ON CONFLICT ("Username") DO UPDATE
SET
    "PasswordHash" = EXCLUDED."PasswordHash",
    "PasswordSalt" = EXCLUDED."PasswordSalt",
    "FirstName" = EXCLUDED."FirstName",
    "LastName"  = EXCLUDED."LastName",
    "Email"     = EXCLUDED."Email",
    "ContactNo" = EXCLUDED."ContactNo",
    "Activated" = EXCLUDED."Activated",
    "CreatedAt" = EXCLUDED."CreatedAt";

-- 4) Seed UserDetails (portfolio summary + skills + video)
INSERT INTO "UserDetails" ("UserId", "Description", "Skills", "Video")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Senior Full-Stack .NET Developer with 19+ years of experience building scalable web applications using .NET, React, Angular, and SQL. Experienced in ERP, banking, and enterprise systems with strong focus on performance and maintainability',
    'C#,.NET Core,AngularJS,Angular,React,.NET Core C#,SQL,cloud-native technologies,AI-assisted development,Cursor,GitHub Copilot,React Native,ASP.NET C#,MVC,MS SQL,MongoDB,Docker,RabbitMQ,Google Cloud Platform,HubSpot,PingIdentity,REST APIs,Azure,Cloud Functions,Datastore,Pub/Sub,ARM/Bicep-style deployments,WCF,EF6,IoC/DI,Bootstrap,Umbraco,ASP Classic,JavaScript,Flash,Telerik controls,ORM,XML,SQL Server,AJAX,VB6,Crystal Reports,VB.NET',
    'https://go.screenpal.com/watch/cOflXKnOnrx'
)
ON CONFLICT ("UserId") DO UPDATE
SET
    "Description" = EXCLUDED."Description",
    "Skills"      = EXCLUDED."Skills",
    "Video"       = EXCLUDED."Video";

-- 5) Seed Projects (matches ProfileController project categories)
INSERT INTO "Project" ("UserId", "Name", "Type", "ProjectDetails")
VALUES
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Enterprise Management System',
    '🧳 Travel Industry Systems',
    'Travel agent management platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Content Management System (Travel)',
    '🧳 Travel Industry Systems',
    'CMS for travel operations'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'MortgageChoice',
    '💰 Finance & Banking Systems',
    'Brokerage management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'CustomerData.Contact',
    '💰 Finance & Banking Systems',
    'Cloud-based customer data microservices (CRM sync)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Tardis Omniverse',
    '💰 Finance & Banking Systems',
    'Lead generation platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Rubik',
    '💰 Finance & Banking Systems',
    'Banking and credit card management system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Internet Banking System',
    '💰 Finance & Banking Systems',
    'Online banking platform (web & mobile)'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Content Management System (Umbraco)',
    '🌐 Web & CMS Platforms',
    'CMS for websites'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Project Management System (AngularJS)',
    '🌐 Web & CMS Platforms',
    'Internal team management tool'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Enterprise Accounting & HR System',
    '🏢 Enterprise & Business Systems',
    'ERP for accounting, HR, purchasing'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Training Management System',
    '🏢 Enterprise & Business Systems',
    'Employee training platform'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Document Management System',
    '🏢 Enterprise & Business Systems',
    'File storage, search, and PDF export system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Client/Project/Task Management System',
    '🏢 Enterprise & Business Systems',
    'Business workflow system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'eCommerce Platform (AspDotNetStorefront)',
    '🛒 E-Commerce & Customer-Facing Apps',
    'Online shopping system'
),
(
    (SELECT "UserId" FROM "User" WHERE "Username" = 'deobernal@gmail.com'),
    'Payment Gateway Integration Enhancements',
    '🛒 E-Commerce & Customer-Facing Apps',
    'Fixes and improvements'
)
ON CONFLICT ("UserId", "Name", "Type") DO UPDATE
SET
    "ProjectDetails" = EXCLUDED."ProjectDetails";

-- 6) Verification queries
SELECT * FROM "User" ORDER BY "UserId";
SELECT * FROM "UserDetails" ORDER BY "UserDetailsId";
SELECT * FROM "Project" ORDER BY "ProjectId";
SELECT * FROM "PasswordResetToken" ORDER BY "TokenId";

-- 7) Incremental: add PasswordResetToken on an existing database (skip if table already exists)
-- CREATE TABLE IF NOT EXISTS "PasswordResetToken"
-- (
--     "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     "UserId"      INTEGER NOT NULL,
--     "Token"       VARCHAR(256) NOT NULL,
--     "ExpiresAt"   TIMESTAMPTZ NOT NULL,
--     "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
--     "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT "FK_PasswordResetToken_User"
--         FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
--         ON DELETE CASCADE
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS "UX_PasswordResetToken_Token" ON "PasswordResetToken" ("Token");

