-- Run against your DMBPortfolio database if registration fails with:
--   PostgresException 42P01: relation "AccountActivationToken" does not exist
-- Safe to run multiple times.

CREATE TABLE IF NOT EXISTS "AccountActivationToken"
(
    "TokenId"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"      INTEGER NOT NULL,
    "Token"       VARCHAR(256) NOT NULL,
    "ExpiresAt"   TIMESTAMPTZ NOT NULL,
    "IsUsed"      BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_AccountActivationToken_User"
        FOREIGN KEY ("UserId") REFERENCES "User" ("UserId")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_AccountActivationToken_Token"
    ON "AccountActivationToken" ("Token");
